
package com.falabella.sodimac.client.CuentaCorrienteSaldoObtenerService;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CuentaCorrienteSaldoObtenerService",
                  targetNamespace = "http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0",
                  wsdlLocation =
                  "http://192.168.1.198:8888/SodimacService-CuentaCorrienteSaldoObtener-context-root/CuentaCorrienteSaldoObtenerPort?WSDL#%7Bhttp%3A%2F%2Fmdwcorp.falabella.com%2FSOD%2FCL%2FOSB%2Fwsdl%2FCuentacorriente%2FSaldo%2FObtener-v1.0%7DCuentaCorrienteSaldoObtenerService")
public class CuentaCorrienteSaldoObtenerService extends Service {

    private final static URL CUENTACORRIENTESALDOOBTENERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUENTACORRIENTESALDOOBTENERSERVICE_EXCEPTION;
    private final static QName CUENTACORRIENTESALDOOBTENERSERVICE_QNAME =
        new QName("http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0",
                  "CuentaCorrienteSaldoObtenerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://192.168.1.198:8888/SodimacService-CuentaCorrienteSaldoObtener-context-root/CuentaCorrienteSaldoObtenerPort?WSDL#%7Bhttp%3A%2F%2Fmdwcorp.falabella.com%2FSOD%2FCL%2FOSB%2Fwsdl%2FCuentacorriente%2FSaldo%2FObtener-v1.0%7DCuentaCorrienteSaldoObtenerService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUENTACORRIENTESALDOOBTENERSERVICE_WSDL_LOCATION = url;
        CUENTACORRIENTESALDOOBTENERSERVICE_EXCEPTION = e;
    }

    public CuentaCorrienteSaldoObtenerService() {
        super(__getWsdlLocation(), CUENTACORRIENTESALDOOBTENERSERVICE_QNAME);
    }

    public CuentaCorrienteSaldoObtenerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUENTACORRIENTESALDOOBTENERSERVICE_QNAME, features);
    }

    public CuentaCorrienteSaldoObtenerService(URL wsdlLocation) {
        super(wsdlLocation, CUENTACORRIENTESALDOOBTENERSERVICE_QNAME);
    }

    public CuentaCorrienteSaldoObtenerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUENTACORRIENTESALDOOBTENERSERVICE_QNAME, features);
    }

    public CuentaCorrienteSaldoObtenerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CuentaCorrienteSaldoObtenerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CuentaCorrienteSaldoObtenerPt
     */
    @WebEndpoint(name = "CuentaCorrienteSaldoObtenerPort")
    public CuentaCorrienteSaldoObtenerPt getCuentaCorrienteSaldoObtenerPort() {
        return super.getPort(new QName("http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0",
                                       "CuentaCorrienteSaldoObtenerPort"), CuentaCorrienteSaldoObtenerPt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CuentaCorrienteSaldoObtenerPt
     */
    @WebEndpoint(name = "CuentaCorrienteSaldoObtenerPort")
    public CuentaCorrienteSaldoObtenerPt getCuentaCorrienteSaldoObtenerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0",
                                       "CuentaCorrienteSaldoObtenerPort"), CuentaCorrienteSaldoObtenerPt.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CUENTACORRIENTESALDOOBTENERSERVICE_EXCEPTION != null) {
            throw CUENTACORRIENTESALDOOBTENERSERVICE_EXCEPTION;
        }
        return CUENTACORRIENTESALDOOBTENERSERVICE_WSDL_LOCATION;
    }

}
