package com.falabella.sodimac.client.CuentaCorrienteSaldoObtenerService;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c Development Build 12.2.1.1.0.2047
public class CuentaCorrienteSaldoObtenerPortClient {
    public static void main(String[] args) {
        CuentaCorrienteSaldoObtenerService cuentaCorrienteSaldoObtenerService =
            new CuentaCorrienteSaldoObtenerService();
        CuentaCorrienteSaldoObtenerPt cuentaCorrienteSaldoObtenerPt =
            cuentaCorrienteSaldoObtenerService.getCuentaCorrienteSaldoObtenerPort();
        // Add your code to call the desired methods.


    }
}
