
package com.falabella.sodimac.client.CuentaCorrienteSaldoObtenerService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

import com.falabella.sodimac.client.CuentaCorrienteSaldoObtenerService.types.CuentaCorrienteSaldoObtenerExpReqTYPE;
import com.falabella.sodimac.client.CuentaCorrienteSaldoObtenerService.types.CuentaCorrienteSaldoObtenerExpRespTYPE;
import com.falabella.sodimac.client.CuentaCorrienteSaldoObtenerService.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "CuentaCorrienteSaldoObtenerPt",
            targetNamespace = "http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface CuentaCorrienteSaldoObtenerPt {


    /**
     *
     * @param cuentaCorrienteSaldoObtenerReqParam
     * @return
     *     returns com.falabella.sodimac.client.CuentaCorrienteSaldoObtenerService.types.CuentaCorrienteSaldoObtenerExpRespTYPE
     * @throws FaultMsg
     */
    @WebMethod(operationName = "CuentaCorrienteSaldoObtenerOp",
               action = "http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0/Op")
    @WebResult(name = "cuentaCorrienteSaldoObtenerExpResp",
               targetNamespace =
               "http://mdwcorp.falabella.com/SOD/CL/OSB/schema/Cuentacorriente/Saldo/Obtener/Resp-v2016.07",
               partName = "cuentaCorrienteSaldoObtenerRespParam")
    @Action(input = "http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0/Op",
            output =
            "http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0/CuentaCorrienteSaldoObtenerPt/CuentaCorrienteSaldoObtenerOpResponse",
            fault =
            { @FaultAction(className = FaultMsg.class,
                           value =
                           "http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0/CuentaCorrienteSaldoObtenerPt/CuentaCorrienteSaldoObtenerOp/Fault/FaultMsg") })
    public CuentaCorrienteSaldoObtenerExpRespTYPE cuentaCorrienteSaldoObtenerOp(@WebParam(name =
                                                                                          "cuentaCorrienteSaldoObtenerExpReq",
                                                                                          targetNamespace =
                                                                                          "http://mdwcorp.falabella.com/SOD/CL/OSB/schema/Cuentacorriente/Saldo/Obtener/Req-v2016.07",
                                                                                          partName =
                                                                                          "cuentaCorrienteSaldoObtenerReqParam")
                                                                                CuentaCorrienteSaldoObtenerExpReqTYPE cuentaCorrienteSaldoObtenerReqParam) throws FaultMsg;

}
