package com.falabella.sodimac.client.ClienteEmpresaDocumentosObtenerService;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c Development Build 12.2.1.1.0.2047
public class ClienteEmpresaDocumentosObtenerPortClient {
    public static void main(String[] args) {
        ClienteEmpresaDocumentosObtenerService clienteEmpresaDocumentosObtenerService =
            new ClienteEmpresaDocumentosObtenerService();
        ClienteEntregaDocumentosObtenerPt clienteEntregaDocumentosObtenerPt =
            clienteEmpresaDocumentosObtenerService.getClienteEmpresaDocumentosObtenerPort();
        // Add your code to call the desired methods.


    }
}
