
package com.falabella.sodimac.client.ClienteEmpresaDocumentosObtenerService;

import javax.xml.ws.WebFault;

import com.falabella.sodimac.client.ClienteEmpresaDocumentosObtenerService.types.Fault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebFault(name = "Fault", targetNamespace = "http://schemas.xmlsoap.org/soap/envelope/")
public class FaultMsg extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private Fault faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public FaultMsg(String message, Fault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FaultMsg(String message, Fault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: com.falabella.sodimac.client.ClienteEmpresaDocumentosObtenerService.types.Fault
     */
    public Fault getFaultInfo() {
        return faultInfo;
    }

}
