
package com.falabella.mdwcorp.sod.cl.osb.wsdl.clienteempresa.documentos.obtener_v1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ClienteEmpresaDocumentosObtenerService",
                  targetNamespace =
                  "http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Clienteempresa/Documentos/Obtener-v1.0",
                  wsdlLocation =
                  "http://127.0.0.1:8888/SodimacService-ClienteEmpresaDocumentosObtener-context-root/ClienteEmpresaDocumentosObtenerPort?WSDL#%7Bhttp%3A%2F%2Fmdwcorp.falabella.com%2FSOD%2FCL%2FOSB%2Fwsdl%2FClienteempresa%2FDocumentos%2FObtener-v1.0%7DClienteEmpresaDocumentosObtenerService")
public class ClienteEmpresaDocumentosObtenerService extends Service {

    private final static URL CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_EXCEPTION;
    private final static QName CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_QNAME =
        new QName("http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Clienteempresa/Documentos/Obtener-v1.0",
                  "ClienteEmpresaDocumentosObtenerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://127.0.0.1:8888/SodimacService-ClienteEmpresaDocumentosObtener-context-root/ClienteEmpresaDocumentosObtenerPort?WSDL#%7Bhttp%3A%2F%2Fmdwcorp.falabella.com%2FSOD%2FCL%2FOSB%2Fwsdl%2FClienteempresa%2FDocumentos%2FObtener-v1.0%7DClienteEmpresaDocumentosObtenerService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_WSDL_LOCATION = url;
        CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_EXCEPTION = e;
    }

    public ClienteEmpresaDocumentosObtenerService() {
        super(__getWsdlLocation(), CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_QNAME);
    }

    public ClienteEmpresaDocumentosObtenerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_QNAME, features);
    }

    public ClienteEmpresaDocumentosObtenerService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_QNAME);
    }

    public ClienteEmpresaDocumentosObtenerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_QNAME, features);
    }

    public ClienteEmpresaDocumentosObtenerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteEmpresaDocumentosObtenerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ClienteEntregaDocumentosObtenerPt
     */
    @WebEndpoint(name = "ClienteEmpresaDocumentosObtenerPort")
    public ClienteEntregaDocumentosObtenerPt getClienteEmpresaDocumentosObtenerPort() {
        return super.getPort(new QName("http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Clienteempresa/Documentos/Obtener-v1.0",
                                       "ClienteEmpresaDocumentosObtenerPort"), ClienteEntregaDocumentosObtenerPt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteEntregaDocumentosObtenerPt
     */
    @WebEndpoint(name = "ClienteEmpresaDocumentosObtenerPort")
    public ClienteEntregaDocumentosObtenerPt getClienteEmpresaDocumentosObtenerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Clienteempresa/Documentos/Obtener-v1.0",
                                       "ClienteEmpresaDocumentosObtenerPort"), ClienteEntregaDocumentosObtenerPt.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_EXCEPTION != null) {
            throw CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_EXCEPTION;
        }
        return CLIENTEEMPRESADOCUMENTOSOBTENERSERVICE_WSDL_LOCATION;
    }

}
