<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0" name="CuentaCorrienteSaldoObtenerService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://mdwcorp.falabella.com/SOD/CL/OSB/schema/Cuentacorriente/Saldo/Obtener/Req-v2016.07" schemaLocation="CuentaCorrienteSaldoObtenerPort1.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://mdwcorp.falabella.com/SOD/CL/OSB/schema/Cuentacorriente/Saldo/Obtener/Resp-v2016.07" schemaLocation="CuentaCorrienteSaldoObtenerPort2.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://schemas.xmlsoap.org/soap/envelope/" schemaLocation="CuentaCorrienteSaldoObtenerPort3.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://mdwcorp.falabella.com/common/schema/clientservice" schemaLocation="CuentaCorrienteSaldoObtenerPort4.xsd"/>
    </xsd:schema>
  </types>
  <message name="CuentaCorrienteSaldoObtenerOp">
    <part xmlns:ns1="http://mdwcorp.falabella.com/SOD/CL/OSB/schema/Cuentacorriente/Saldo/Obtener/Req-v2016.07" name="cuentaCorrienteSaldoObtenerReqParam" element="ns1:cuentaCorrienteSaldoObtenerExpReq"/>
  </message>
  <message name="CuentaCorrienteSaldoObtenerOpResponse">
    <part xmlns:ns2="http://mdwcorp.falabella.com/SOD/CL/OSB/schema/Cuentacorriente/Saldo/Obtener/Resp-v2016.07" name="cuentaCorrienteSaldoObtenerRespParam" element="ns2:cuentaCorrienteSaldoObtenerExpResp"/>
  </message>
  <message name="FaultMsg">
    <part xmlns:ns3="http://schemas.xmlsoap.org/soap/envelope/" name="fault" element="ns3:Fault"/>
  </message>
  <portType name="CuentaCorrienteSaldoObtenerPt">
    <operation name="CuentaCorrienteSaldoObtenerOp">
      <input wsam:Action="http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0/Op" message="tns:CuentaCorrienteSaldoObtenerOp"/>
      <output wsam:Action="http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0/CuentaCorrienteSaldoObtenerPt/CuentaCorrienteSaldoObtenerOpResponse" message="tns:CuentaCorrienteSaldoObtenerOpResponse"/>
      <fault message="tns:FaultMsg" name="FaultMsg" wsam:Action="http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0/CuentaCorrienteSaldoObtenerPt/CuentaCorrienteSaldoObtenerOp/Fault/FaultMsg"/>
    </operation>
  </portType>
  <binding name="CuentaCorrienteSaldoObtenerPortBinding" type="tns:CuentaCorrienteSaldoObtenerPt">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="CuentaCorrienteSaldoObtenerOp">
      <soap:operation soapAction="http://mdwcorp.falabella.com/SOD/CL/OSB/wsdl/Cuentacorriente/Saldo/Obtener-v1.0/Op"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="FaultMsg">
        <soap:fault name="FaultMsg" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="CuentaCorrienteSaldoObtenerService">
    <port name="CuentaCorrienteSaldoObtenerPort" binding="tns:CuentaCorrienteSaldoObtenerPortBinding">
      <soap:address location="http://127.0.0.1:8888/SodimacService-CuentaCorrienteSaldoObtener-context-root/CuentaCorrienteSaldoObtenerPort"/>
    </port>
  </service>
</definitions>